FROM openjdk:17-alpine

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    APP_SLEEP=5 \
    JAVA_OPTS=""

# Add an app user to run our application so that it doesn't need to run as root
RUN adduser -D -s /bin/sh userapp
WORKDIR /home/userapp

ADD entrypoint.sh entrypoint.sh
RUN chmod 755 entrypoint.sh && chown userapp:userapp entrypoint.sh
USER userapp

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 8081